//
// This file is a part of the Chunk Stories API codebase
// Check out README.md for more information
// Website: http://chunkstories.xyz
//

package io.xol.chunkstories.api.client;

/** Parameters of the client are expose through this mostly autogenerated interface. 
 *  This is to avoid costly access and parsing of these common parameters at frame time
 * 	Very subject to change in new revisions !
 * */
public interface ClientRenderingConfig {

	float getViewDistance();

	float getFogDistance();

	boolean isDynamicGrass();

	boolean isHqTerrain();

	boolean isPerPixelFresnel();

	boolean isDoShadows();

	boolean isDoBloom();

	boolean isDoClouds();

	int getShadowMapResolutions();

	int getSsaoQuality();

	boolean isDoRealtimeReflections();

	boolean isPhysicsVisualization();

	boolean isShowDebugInfo();

	float getMouseSensitivity();

	float getFov();

	boolean isDoDynamicCubemaps();

	int getAnimationCacheMaxSize();

	int getAnimationCacheFrameRate();

	boolean isDebugAllowed();

}